options:
    Spawn: 4565, 106, -8505
	#Recommended to keep > 200
    MaxTreeSize: 200

    MaxGoldOre: 3
    MaxIronOre: 2
    MaxCoal: 4
    MaxLapis: 3
    MaxDiamond: 2
    MaxRedstone: 5
    MaxEmerald: 2
    MaxQuartz: 1.75

#command /yamler:
#	trigger:
#		if yml /servers/hub/plugins/Jobs/TranslatableWords in file /servers/hub/plugins/Jobs/TranslatableWords exists:
#			 if contains "%type of player's targeted block%"

#========[¤]========#
#					#
#	   Finances    	#
#					#
#========[¤]========#
#set {louvre_break_sign} to location at -9761, 73, 2357 of the world "gaia"
#set line 3 of block at {louvre_break_sign} to "%{block.breaks.louvre}%"

on block break:
	if event-block is any ore or any log:
		message "hello"

command /urler:
	trigger:
		set {_level} to placeholder "betonquest_default:point.reputation.amount" from player
		message "%{_level}% pts"
		set {_temp} to 64 brick named "&aTablette" with lore "&7Cette tablette est" and "&7composée de minerais" and "&7précieux, et regorge" and "&7d'un pouvoir de traction." and " " and "&7&oRareté : &aNon-Commun"
		set {_mess} to {_temp} 
		message {_mess}
		set {_mess2} to player's tool
		message {_mess2}
		#give player {_temp}
		if player has 32 brick:
			message "yello"
			remove 32 brick from the player's inventory
		
command /testtp:
	trigger:
		close player's inventory
		set {_temp} to distance between location at {@Spawn} in world "gaia" and player
		message {_temp}
		if player has {_item}:
			wait 5 seconds
			teleport player to location at {_location}
		else:
			message "&7Vous n'avez pas assez de tablettes pour vous téléporter à cette distance."

command /soundar:
	trigger:
		#play resource sound pack "battle" to player [at %location%] [(and|with) volume %number%] [(and|with) pitch %number%]
		#play sound "battle" with volume 0.5 to player
		apply potion of blindness 1 to the player for 15 seconds
		apply potion of night vision 1 to the player for 6 seconds

		async
		ActionBarSend(player,"&4Pensez à utiliser le resource pack!")
		play resource sound pack "gaia_intro" to player with volume 3
		send title "&6Bienvenue" with subtitle "&esur Gaïa Renaissance" to player for 10 seconds with fadein 2 second and fade out 2 second
		#async 
		#play resource sound pack "chop" to player with volume 1
		


command /playerinfo:
	trigger:
		loop all players:
			message "%loop-player%"
		#loop entities in radius 5 around player's location:
		#	message "%loop-entity%"
		#	if "%loop-entity%" contains "armor":	
		#		kill loop-entity


command /checking:
	trigger:
		set {_type} to type of player's tool
		message "%{_type}%"
		#drop 1 charcoal named "&fRésidus d'acajou" with lore "&7Des copeaux de bois" and "&7d'un acajou de faible qualité." and " " and "&7Rareté : &fCommun" at player's location
		message "You have %number of ore in player's inventory% ores in your inventory."
		loop a random integer between 1 and {@MaxGoldOre} * {@MaxQuartz} times:
			broadcast "%{@MaxGoldOre} * {@MaxQuartz}%"
		set {_init} to random integer between 1 and 100
		set {_luck} to random integer between 1 and 100
		set {_random} to ({_init} / 100 * 50)
		message "%{_init}% & %{_random}% & %{_luck}%"
		if {_luck} <= {_random}:
			ActionBarSend(player, "Hey {@MaxQuartz}")
		loop ceil({_undefined} * {@MaxQuartz}) times:
			message "ceil"
		loop 0 times:
			message "0"
		set {_mineur.level} to placeholder "jobs_level_Mineur" from player parsed as integer
		message "%{_mineur.level}%"


command /permcheck <string>:
    trigger:
        if player has permission "%arg 1%":
            message "got it !"
        loop all of the bungeecord players:
            set {_player} to loop-value parsed as offline player
            set {_uuid} to {_player}'s uuid
            message "Tu vois ce message UNIQUE %loop-value% ? =)" to bungeecord player "%offline player from uuid {_uuid}%"
        message "&7Une nouvelle élection vient de commencer au sein de votre race." to all of the bungeecord players
        skungee send "&7Utilisez &8/elections info &7pour plus d'informations." to all of the bungeecord players

#on command "discord unlink":
#    if current server contains "hub":
#        if player has permission "discordsrv.sync.288492806618611712":
#            cancel event
#            message "&7Vos comptes vont être déliés."
#            message "&7Suppression des grades sur le Discord en cours..."
#            message "&7Veuillez patienter..."
#            execute console command "lp user %player% permission settemp discordsrv.sync.288492806618611712 false 10m"
#            set {_integer} to 0
#            loop 4 times:
#                wait 1 second
#                set {_lower} to {_integer}
#                add 25 to {_integer}
#                message "%random integer between {_lower} and {_integer}% %%"

#            make player execute command "discord unlink"

command /statis:
    trigger:
        message "jobs_jobs : %placeholder ""jobs_jobs"" from player%"
        message "jobs_format: %placeholder ""jobs_format"" from player%"
        message "region :%region at location at player%"
        if "%region at location at player%" contains "resource":
            message "it does"
        #
        message "jobs_level_Bûcheron: %placeholder ""jobs_level_Bûcheron"" from player%"
        message "jobs_level_Mineur: %placeholder ""jobs_level_Artisan"" from player%"
        set {_p1} to placeholder "jobs_level_Mineur" from player parsed as integer
        set {_p2} to placeholder "jobs_level_Bûcheron" from player parsed as integer
        if {_p1} >= 1:
            message "should not"
        if {_p2} >= 1:
            message "yello"

        message "heroes_level: %placeholder ""heroes_class"" from player%"
        message "heroes_main_class_name: %placeholder ""heroes_class2"" from player%"
        message "heroes_second_class_name: %placeholder ""heroes_class_level"" from player%"


command /tree <string>:
    trigger:
        if arg 1 is "info":
            message "info"
            loop tree at location at targeted block:
                message "1"
                add 1 to {_count}
                if {_count} < 200:
                    broadcast "%loop-value%"
                else:
                    message "2"
                    stop

        else if arg 1 is "gen":
            broadcast "gen"
            #grow a tall redwood tree above the targeted block

        else if arg 1 is "del":
            #remove tree at the location at targeted block
            loop tree at location at targeted block:
                add type of loop-value to {_tree::*}
                add location at loop-value to {_location::*}
                set block at location at loop-value to air
            wait 2 seconds
            loop {_tree::*}:
                broadcast "%loop-value%"
                set block at location at {_location::%loop-index%} to loop-value
command /execute:
    trigger:
        make player execute command "progression"


command /apart:
    trigger:
        async:
            set {_loc} to event-location
            drawRings particle "redstone", speed 1, RGB 255, 255, 255, center {_loc}, id "tester1", randomRotation true, animated true, radius 1, ringCount 4, ringDensity 1, visibleRange 32
            drawDot count 50, particle "mobspell", XYZ 255, 255, 255, center {_loc}, visibleRange 32, pulseDelay 1, keepFor 10 seconds
            #draw 10 colored redstone particles at player with RGB 255, 255, 255, visibleRange 10, keepFor 60 ticks
            #drawDot count 10, particle "redstone", RGB 255, 255, 255, center player, visibleRange 10, pulseDelay 5, keepFor 100 ticks
            wait 10 seconds
            stopEffect id "tester1"

command /drawDotEx:
	trigger:
		set {_loc} to event-location
		broadcast "&8[&eskDragon&8]&a&l drawDot syntax examples about to begin, step back a few blocks"
		wait 3 second
		broadcast "&8[&eskDragon&8]&a&l-Example 1-  50 'non colored' particles with offset of '1, 1, 1' and a different pulseDelay each"
		wait 2 second
		broadcast "&b&l3"
		wait 1 second
		broadcast "&b&l2"
		wait 1 second
		broadcast "&b&l1"
		wait 1 second
		drawDot count 50, particle "smoke", XYZ 1, 1, 1, center {_loc}, visibleRange 32, keepFor 5 seconds
		wait 5 seconds
		# Offset is both RGB and XYZ, they are both one in the same
		drawDot count 50, particle "flame", speed 1, RGB 1, 1, 1, center {_loc}, visibleRange 32, pulseDelay 1, keepFor 5 seconds
		wait 5 seconds
		drawDot count 50, particle "heart", speed 10, XYZ 1, 1, 1, center {_loc}, visibleRange 32, pulseDelay 3, keepFor 5 seconds
		wait 5 seconds
		drawDot count 50, particle "itemcrack", material diamond, XYZ 1, 1, 1, center {_loc}, visibleRange 32, pulseDelay 5, keepFor 5 seconds
		wait 5 seconds
		broadcast "&8[&eskDragon&8]&a&l-Example 2- 1 'non colored' particle with offset of 0, 0, 0 and a different pulseDelay each"
		wait 2 second
		broadcast "&b&l3"
		wait 1 second
		broadcast "&b&l2"
		wait 1 second
		broadcast "&b&l1"
		wait 1 second
		drawDot count 1, particle "smoke", RGB 0, 0, 0, center {_loc}, visibleRange 32, keepFor 5 seconds
		wait 5 seconds
		drawDot count 1, particle "flame", XYZ 0, 0, 0, center {_loc}, visibleRange 32, pulseDelay 1, keepFor 5 seconds
		wait 5 seconds
		drawDot count 1, particle "heart", XYZ 0, 0, 0, center {_loc}, visibleRange 32, pulseDelay 3, keepFor 5 seconds
		wait 5 seconds
		drawDot count 1, particle "itemcrack", material wooden sword, XYZ 0, 0, 0, center {_loc}, visibleRange 32, pulseDelay 5, keepFor 5 seconds
		wait 5 seconds
		broadcast "&8[&eskDragon&8]&a&l-Example 3- 1 'colored' particle with different offset values"
		wait 2 second
		broadcast "&b&l3"
		wait 1 second
		broadcast "&b&l2"
		wait 1 second
		broadcast "&b&l1"
		wait 1 second
		# These particles(except note) accept any value from 0 - 255 for offset color (notice how XYZ and RGB in the syntax do the same thing)
		# A value of '0, 0, 0' will produce a black color/shade
		drawDot count 50, particle "redstone", RGB 0, 0, 0, center {_loc}, visibleRange 32, keepFor 5 seconds
		wait 5 seconds
		drawDot count 50, particle "mobspell", XYZ 0, 0, 255, center {_loc}, visibleRange 32, pulseDelay 1, keepFor 5 seconds
		wait 5 seconds
		drawDot count 50, particle "mobspellambient", XYZ 0, 255, 0, center {_loc}, visibleRange 32, pulseDelay 3, keepFor 5 seconds
		wait 5 seconds
		# Note particles ONLY accept an 'X' or 'R' offset value from 0 - 24
		drawDot count 50, particle "note", XYZ 12, 0, 0, center {_loc}, visibleRange 32, pulseDelay 5, keepFor 5 seconds
		wait 5 seconds
		broadcast "&8[&eskDragon&8]&a&l-Example 4- 1 'colored' particle with rainbowMode true and extended time"
		wait 2 second
		broadcast "&b&l3"
		wait 1 second
		broadcast "&b&l2"
		wait 1 second
		broadcast "&b&l1"
		wait 1 second
		# Any offset value will be ignored when rainbowMode is set to true
		drawDot count 50, particle "redstone", RGB 0, 0, 0, center {_loc}, rainbowMode true, visibleRange 32, keepFor 8 seconds
		wait 8 seconds
		drawDot count 50, particle "mobspell", XYZ 0, 255, 0, center {_loc}, rainbowMode true, visibleRange 32, pulseDelay 1, keepFor 8 seconds
		wait 8 seconds
		drawDot count 50, particle "mobspellambient", XYZ 0, 0, 255, center {_loc}, rainbowMode true, visibleRange 32, pulseDelay 3, keepFor 8 seconds
		wait 8 seconds
		drawDot count 50, particle "note", XYZ 0, 0, 0, center {_loc}, rainbowMode true, visibleRange 32, pulseDelay 5, keepFor 8 seconds
		wait 8 seconds
		broadcast "&c&lDone!  :)"

#========[¤]========#
#					#
#		 Chat		#
#					#
#========[¤]========#

#
# This is unused since ChatControl & DiscordSRV manage most of chat & BungeeChat.
#	This can be used for further messaging as later add-on.
#

command /justchat:
	trigger:
		skungee message "yellow" to all of the bungeecord players
		skungee message "yellow2" to bungeecord player "hollishkid"



command /tablist:
	trigger:
		set amount of columns in player's array tablist to 4
		set amount of rows in player's tablist to 10
		loop all bungeecord players:
			set {_player} to loop-value
			message "%{_player}%"
		set tablist header of bungeecord player player to "&aGaïa MMORPG - Renaissance%nl%&7Discord : discord.gaia-craft" and "&7---------- &8¤ &7----------"
		#set tablist footer of bungeecord player "hollishkid" to "yellow2!" and "yellow again2"
		
command /changeserver <string>:
	trigger:
		connect bungeecord player "hollishkid" to server arg 1
		
command /sometext:
	trigger:
		message "%all of the bungeecord players%"
		if bungeecord player "%player%" is running the forge client:
			message "Gotcha! Vous utilisez un client moddé !"
		else:
			message "Soit vous n'avez pas de client moddé, soit vous nous le chachez :thinking:"

command /chatting <offline player>:
	trigger:
		set {_uuid} to arg 1's uuid
		
		#replace here the {_uuid} with the loop value from a list of people in a channel.
		if bungeecord player "%offline player from uuid {_uuid}%" is online:
			message "online seen" to bungeecord player "%offline player from uuid {_uuid}%"
		else:
			message "OFF" to console