#========[¤]========#
#					#
#		Tâches		#
#					#
#========[¤]========#

#
# Specific to this server tasks.
#

#
# On First Join
#
on first join:
	set join message to ""

#
# On Join
#
on join:
	set join message to "&8%player% &7a rejoint Thol Guthix."

#
# On Quit
#
on quit:
	set leave message to "&8%player% &7a quitté Thol Guthix."
	set {_uuid} to player's uuid
	loop tree of {local::temp::%{_uuid}%::*}:
		delete {local::temp::%{_uuid}%::%branch%}